//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Southernfund.UpdateSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UP_ADMINUSER
    {
        public UP_ADMINUSER()
        {
            this.UP_USERINROLE = new HashSet<UP_USERINROLE>();
        }
    
        public string id { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
        public string realname { get; set; }
        public int sex { get; set; }
        public string phone { get; set; }
        public Nullable<int> type { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public int department { get; set; }
        public bool isdisabled { get; set; }
        public bool isvalidate { get; set; }
        public string merid { get; set; }
    
        public virtual ICollection<UP_USERINROLE> UP_USERINROLE { get; set; }
    }
}
