//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Southernfund.UpdateSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UP_PROJECT
    {
        public UP_PROJECT()
        {
            this.UP_UPDATE = new HashSet<UP_UPDATE>();
        }
    
        public string id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public bool disable { get; set; }
        public int type { get; set; }
        public string description { get; set; }
        public string remark { get; set; }
        public string downloadserverurl { get; set; }
    
        public virtual ICollection<UP_UPDATE> UP_UPDATE { get; set; }
    }
}
