//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Southernfund.UpdateSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UP_ROLE
    {
        public UP_ROLE()
        {
            this.UP_USERINROLE = new HashSet<UP_USERINROLE>();
        }
    
        public string rlid { get; set; }
        public Nullable<int> merid { get; set; }
        public string name { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string modifiedby { get; set; }
        public bool is_validate { get; set; }
    
        public virtual ICollection<UP_USERINROLE> UP_USERINROLE { get; set; }
    }
}
