//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Southernfund.UpdateSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UP_USERINROLE
    {
        public string urid { get; set; }
        public string usid { get; set; }
        public string rlid { get; set; }
    
        public virtual UP_ADMINUSER UP_ADMINUSER { get; set; }
        public virtual UP_ROLE UP_ROLE { get; set; }
    }
}
